// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZI0YXZijJWBZCrbf7OzNF1p9UQYHl2oc',
    appId: '1:193097301897:web:23d170703ce44008f6ab58',
    messagingSenderId: '193097301897',
    projectId: 'auth-fb642',
    authDomain: 'auth-fb642.firebaseapp.com',
    databaseURL: 'https://auth-fb642-default-rtdb.firebaseio.com',
    storageBucket: 'auth-fb642.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU-WG7rmLRjBnaG9nep0fpo6eViA1xuYs',
    appId: '1:193097301897:android:929d579a866455f7f6ab58',
    messagingSenderId: '193097301897',
    projectId: 'auth-fb642',
    databaseURL: 'https://auth-fb642-default-rtdb.firebaseio.com',
    storageBucket: 'auth-fb642.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYwDEcdnRV1KVVe-ToyKYliPBQB30JxpQ',
    appId: '1:193097301897:ios:e9c5fe6f69119d05f6ab58',
    messagingSenderId: '193097301897',
    projectId: 'auth-fb642',
    databaseURL: 'https://auth-fb642-default-rtdb.firebaseio.com',
    storageBucket: 'auth-fb642.appspot.com',
    iosBundleId: 'com.example.flutterLoginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYwDEcdnRV1KVVe-ToyKYliPBQB30JxpQ',
    appId: '1:193097301897:ios:9ae1cf3a38d4d60af6ab58',
    messagingSenderId: '193097301897',
    projectId: 'auth-fb642',
    databaseURL: 'https://auth-fb642-default-rtdb.firebaseio.com',
    storageBucket: 'auth-fb642.appspot.com',
    iosBundleId: 'com.example.flutterLoginPage.RunnerTests',
  );
}
